apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-update-rolebinding-{{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: configmap-updater-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: configmap-update-role-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io