apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-update-role-{{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
