apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: 8769
      targetPort: 8769
      name: http
  selector:
    app: {{ .Release.Name }}